### PR TITLE
set charset for static files properly

### PR DESCRIPTION
**Pull request by timosha**

### CODE REVIEW

**Comment by dimikot** [comment]
This commit breaks auto-tests (at least 400_iframe.phpt and 410_script.phpt). Could you please include patches for tests to this pull request too? (To run auto-tests, install PHP, PEAR and then run run_all.sh at t/servertest.)

**Comment by timosha** [comment]
done

**Comment by dimikot** [comment]
Thanks a lot!
I'll process it on Sat.

**Comment by dimikot** [comment]
Applied. Thank you.

**Pull request merged**
